server:
  port: 8081

spring:
  activemq:
    broker-url: tcp://localhost:61616
    username: artemis
    password: artemis
    topic-name: first-topic
    packages:
      trust-all: true
  artemis:
    embedded:
      queues: queue-data
